import { useState, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-toastify';
import { ArrowRight } from 'lucide-react';
import {
  DrawerOverlay,
  DrawerContainer,
  DrawerHeader,
  HeaderTop,
  ProjectTag,
  CloseButton,
  DrawerTitle,
  DrawerSubtitle,
  DrawerContent,
  Section,
  InputGroup,
  InputLabel,
  TitleInput,
  KeyInputWrapper,
  KeyInput,
  AutoBadge,
  Divider,
  DescriptionTextarea,
  DrawerFooter,
  FooterLeft,
  BackButton,
  CreateButton,
} from './CreateProjectDrawer.styles';
import {
  useCreateProjectMutation,
} from '../../../reducers/slices/project/project.apiSlice';
import { logger } from '../../../utils/logger';

const generateProjectKey = (name) => {
  if (!name) return '';
  const words = name.trim().split(/\s+/);
  if (words.length >= 2) {
    return words.slice(0, 2).map(w => w[0]).join('').toUpperCase();
  }
  return name.slice(0, 3).toUpperCase();
};

const CreateProjectDrawer = ({ isOpen, onClose }) => {
  const navigate = useNavigate();
  const [name, setName] = useState('');
  const [key, setKey] = useState('');
  const [description, setDescription] = useState('');
  const [isKeyManuallyEdited, setIsKeyManuallyEdited] = useState(false);

  const [createProject, { isLoading: isCreating }] = useCreateProjectMutation();

  // Auto-generate key from name
  const autoGeneratedKey = useMemo(() => generateProjectKey(name), [name]);

  // Use manual key if edited, otherwise use auto-generated
  const displayKey = isKeyManuallyEdited ? key : autoGeneratedKey;

  const handleNameChange = (e) => {
    setName(e.target.value);
    if (!isKeyManuallyEdited) {
      setKey('');
    }
  };

  const handleKeyChange = (e) => {
    setKey(e.target.value.toUpperCase());
    setIsKeyManuallyEdited(true);
  };

  const handleCreateProject = async () => {
    if (!name.trim()) {
      toast.error('Project name is required');
      return;
    }

    if (!displayKey.trim()) {
      toast.error('Project key is required');
      return;
    }

    try {
      const result = await createProject({
        name: name.trim(),
        key: displayKey.toUpperCase(),
        description: description.trim() || undefined,
      }).unwrap();

      toast.success('Project created successfully');
      handleClose();
      navigate(`/project/${result.data.id}`);
    } catch (error) {
      logger.apiError('Project creation', error);
      toast.error(error.data?.message || 'Failed to create project');
    }
  };

  const handleClose = () => {
    setName('');
    setKey('');
    setDescription('');
    setIsKeyManuallyEdited(false);
    onClose();
  };

  const handleOverlayClick = (e) => {
    if (e.target === e.currentTarget) {
      handleClose();
    }
  };

  if (!isOpen) return null;

  return (
    <>
      <DrawerOverlay onClick={handleOverlayClick} />
      <DrawerContainer>
        <DrawerHeader>
          <HeaderTop>
            <ProjectTag>Studio Projects</ProjectTag>
            <CloseButton onClick={handleClose} aria-label="Close drawer">
              ×
            </CloseButton>
          </HeaderTop>
          <DrawerTitle>Create New Project</DrawerTitle>
          <DrawerSubtitle>Set up your workspace to get started.</DrawerSubtitle>
        </DrawerHeader>

        <DrawerContent>
          {/* Basic Info Section */}
          <Section>
            <InputGroup>
              <InputLabel>Project Name</InputLabel>
              <TitleInput
                type="text"
                value={name}
                onChange={handleNameChange}
                placeholder="e.g. Apollo Brand Identity"
                disabled={isCreating}
                autoFocus
              />
            </InputGroup>

            <InputGroup>
              <InputLabel>Project Key</InputLabel>
              <KeyInputWrapper>
                <KeyInput
                  type="text"
                  value={displayKey}
                  onChange={handleKeyChange}
                  placeholder="PROJ"
                  maxLength={10}
                  disabled={isCreating}
                />
                {!isKeyManuallyEdited && displayKey && (
                  <AutoBadge>
                    Auto-generated
                  </AutoBadge>
                )}
              </KeyInputWrapper>
            </InputGroup>
          </Section>

          <Divider />

          {/* Description Section */}
          <Section>
            <InputGroup>
              <InputLabel>Description</InputLabel>
              <DescriptionTextarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Describe your project's purpose and goals..."
                disabled={isCreating}
                rows={4}
              />
            </InputGroup>
          </Section>
        </DrawerContent>

        <DrawerFooter>
          <FooterLeft>
            <BackButton onClick={handleClose} disabled={isCreating}>
              Back to Dashboard
            </BackButton>
          </FooterLeft>
          <CreateButton
            onClick={handleCreateProject}
            disabled={isCreating || !name.trim() || !displayKey.trim()}
          >
            {isCreating ? 'Creating...' : 'Get Started'}
            {!isCreating && <ArrowRight size={18} />}
          </CreateButton>
        </DrawerFooter>
      </DrawerContainer>
    </>
  );
};

export default CreateProjectDrawer;
